cmd/build.go, cmd/crossbuild.go, cmd/promu.go, cmd/tarball.go
This also fix the default `build.binaries` config value for `promu crossbuild tarballs` command.
@grobie
=> Move default config values after .promu.yml parsing

cmd/release.go
This gives a feedback of progress for uploading tarballs.
As a side effect, it will prevent timeouts in CircleCI triggered
by no output on stdout for too long.
@sdurrheimer
=> Print tarball upload completion

cmd/promu.go
strings.Fields handles redundant spaces better than strings.Split
=> strings.Fields handles redundant spaces

.promu.yml, circle.yml, cmd/build.go, cmd/crossbuild.go, cmd/promu.go, doc/examples/.promu.yml
Associated with prometheus/golang-builder#13
This PR gives the ability to crossbuild with or without CGO. Non-CGO crossbuilds will be using the golang-builer base image which only contains Golang without any crossbuild toolchains.
Non-CGO builds should be faster now given that there is only a single lighter docker image for all platforms.
The CircleCI fail because it depends on the golang-builder PR. The later must be merged and successfully builded before merging this one.
=> Make CGO optional + use the builder base image for non-cgo

cmd/promu.go
Carriage returns need to be filtered from Windows output. The `shellOutput` function fix solves the output of `whoami` breaking ldflags (#44). Haven't seen any effect of `readFile`, but there should at least be no ill effect.
=> Trim carriage returns in addition to newlines

cmd/crossbuild.go, cmd/promu.go
Apparently, recent MacOS versions really depend on it.
@sdurrheimer @grobie Is there anything else I have to do to build the next Prometheus release with Go1.7.1?
I need to cut a bugfix release ASAP, and I would like to use Go1.7.1 to fix MacOS issues.
=> Bump default Go version to 1.7.1

cmd/build.go, cmd/crossbuild.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/shell_test.go, cmd/tarball.go, util/sh/sh.go
This makes promu successfully compile https://github.com/martinlindhe/wmi_exporter on Windows. Tested on Win 7.
The issues were:
* go-shell swallowed erroring commands, making it harder to debug
* go-shell Run() incorrectly escaped command line parameters, producing impossible command line. 
There is still some dependencies on go-shell, but they seem to be pretty trivial to replace with stdlib code.
Fixes #44 
This was triggered by trying to provide build info to wmi_exporter (https://github.com/martinlindhe/wmi_exporter/issues/24)
=> windows: reduce dependency of go-shell, make build succeed on windows

cmd/build.go
While looking into a failure on appveyor [1], we noticed `command failed: fork/exec c:\go\bin\go.exe: invalid argument`, but appveyor failed to pick up the failure.
This patch quits on command failure using log.Fatal(), which signals an exit code to the OS so it can be picked up by appveyor.
The root cause of the failing command is still under investigation
1: https://ci.appveyor.com/project/martinlindhe/wmi-exporter/build/170
=> return with error code on command failure

cmd/crossbuild.go, cmd/promu.go
(golang-builder was updated in
https://github.com/prometheus/golang-builder/pull/15 )
@sdurrheimer @fabxc
=> Update default Go version to 1.7.3

Makefile
Set GOARCH correctly for ARM devices, e.g. `uname -m` would output `armv7l`
=> support compiling on ARM architectures

cmd/crossbuild.go, cmd/promu.go
@sdurrheimer As far as I can see, golang-builder is prepared for this.
@brian-brazil So that Prometheus 1.5.2 comes compiled with Go 1.7.5.
=> Update Go version to 1.7.5

circle.yml, cmd/checksum.go, cmd/checksum_test.go, cmd/release.go
This is essentially a reimplementation of sha256sum, but removing the
directory name, thus removing the need to use more involved cd/grep
usage in circle.yml files.
I'm not sure if it's worth to reimplement such functionality, but it
reduces the amount of shell scripts and it seems that what we're aiming
for with promu?
Fixes #18 
@sdurrheimer @juliusv @mdlayher
=> Add promu checksum command

cmd/crossbuild.go, cmd/promu.go
+ providing retro-compatibility with existing .promu.yml files via
aliases
Linked to prometheus/golang-builder#28
=> Fix #65 by building only ARM compatible platforms

cmd/check_licenses.go
Problem
It's cumbersome to copy and paste the same shell script file into all of
the various prometheus repositories.  This makes it difficult to make
changes to one and update them everywhere.
Additionally the prometheus project has various different programming
languages such as java, go, ruby, bash, and html.  We need to be able to
run a license check against all of those source files so we need
a configurable way to include them in our check.
Solution
Put the license checking code into promu and use this utility to check
headers everywhere.
This closes #58
=> Feature: Added check_licenses Command to Promu

cmd/info.go, cmd/info_test.go
This makes `promu` support git remote like `ssh://git@git-host:port/namespace/project.git`
=> Fix git repository url parsing

cmd/build.go
Fix https://github.com/prometheus/node_exporter/issues/698 
Install setup from smartos image: base-64-lts 16.4.1
>   pkgin in scmgit-base gcc49
>   pkgin in go-1.9
>   pkgin in git-2.14.1
>   go get github.com/prometheus/node_exporter
>   cd go/src/github.com/prometheus/node_exporter/
>   pkgin in gmake
>   make
Here is the output before this change. 
> formatting code
> vetting code
> running staticcheck
> building binaries
>   node_exporter`
`# github.com/prometheus/node_exporter
/opt/local/go/pkg/tool/solaris_amd64/link: running gcc failed: exit status 1
ld: fatal: library -lsocket: not found
ld: fatal: library -lnsl: not found
ld: fatal: library -lsendfile: not found
ld: fatal: library -lc: not found
ld: fatal: file processing errors. No output written to …
=> Fix build on SmartOS by not setting gcc's -static flag

cmd/crossbuild.go, cmd/promu.go
Update our go version to the latest available release currently requires
touching several files across multiple repositories. Simplify the
process a bit by always using the latest go1.10 minor version regardless
of the specific patch version.
A approval process is still available in prometheus/golang-builder.
@brian-brazil @sdurrheimer
=> Use latest go1.10 patch version by default

vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/vendor.json
As pointed out by @swinslow, the updated version of the library was
changed from LGPLv3 to Apache 2 license, which is easier to handle
legally.
=> Update gopkg.in/yaml.v2 to address license concerns

cmd/build.go, cmd/promu.go
Certain binaries (e.g. node_exporter) require dynamic linking for certain
system functions.  This change adds an option "build.static" to turn off
the default static linking.
Fixes #102
=> [issue #102] Add option to disable static linking

cmd/promu.go
As most shells don't allow dots in environment variable names, it's not
possible to customize nested options via environment variable, like:
PROMU_BUILD_FLAGS='<flags>'
The patch fixes this by asking viper to replace all dots in config key
names with '_' while scanning the environment.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
=> cmd: allow to customize nested options via env variables

.circleci/config.yml, .travis.yml, main_test.go
Overall result was returning success with a failed test when running
tests in package list mode (go test ./...).
Signed-off-by: Paul Gier <pgier@redhat.com>
=> fix test result reporting in package list mode

cmd/crossbuild.go
Fixes #94 
This works when running against a remote Docker engine (for example, in CircleCI), but this _is_ slower, since it adds the step of recursively copying the current working directory into the build container, rather than being bind-mounted in.
Signed-off-by: Dave Henderson <David.Henderson@qlik.com>
=> Avoid bind-mounting to allow building with a remote docker engine

cmd/crossbuild.go
The crossbuild command was copying the .build directory out of the
container and creating a local .build/.build directory.  This
changes the copy operation to correctly get the contents from the
container instead of copying the directory itself.
=> fix crossbuild nested .build directories

cmd/check_licenses.go
Fixs typo:  "extenstions" to "extensions" in line 33.
=> Fixs typo from 'extenstions' to 'extensions'

cmd/build.go, cmd/promu.go, doc/examples/basic/extldflags.yml, main_test.go
This commit implements a new configuration option
for allowing the extldflags to be extended for
specific build requirements (such as additional libraries).
The default case (If no option is provided) remains the same
(the -static flag is passed).
Tests are provided for validating the functionality.
Signed-off-by: Jorge Niedbalski <jorge.niedbalski@linaro.org>
=> Make extldflags extensible by configuration. 

cmd/info.go
Circle-ci git binary version does not have this option.
Since there is little reason we are workinig on a corrupt repo
we can remove this option so that we can build safely on
Circle-ci.
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
=> Remove --broken from git describe

cmd/release.go, cmd/release_test.go
This would facilitate the release process as a maintainer wouldn't have to prepare the GitHub release in advance before pushing a tag (ref Prometheus' [RELEASE.md](https://github.com/prometheus/prometheus/blob/master/RELEASE.md#draft-the-new-release) page). The last manual step will be to push the "Publish release" button.
I tested this change with a repository of mine and it worked fine (see https://github.com/simonpasquier/instrumented_app/releases).
=> cmd/release: create release in GitHub if none exists

Makefile
Overriding the <gopath>/promu target causes a warning during build.
This updates the build to fix the warning and first build promu by
using the go compiler directly, and then using the just built promu
to rebuild itself.
> Makefile:17: warning: overriding recipe for target '/home/pgier/go/bin/promu'
Makefile.common:236: warning: ignoring old recipe for target '/home/pgier/go/bin/promu'
=> Makefile: fix warning

pkg/repository/info.go
see https://github.com/prometheus/promu/pull/170#issuecomment-538327939
=> Support remotes other than "origin"

cmd/crossbuild.go
Add arm64 to the default build of the BSDs.
Fixes: https://github.com/prometheus/memcached_exporter/issues/92
=> Support arm64 on BSDs

cmd/crossbuild.go
Darwin 32-bit x86 is not supported upstream.
=> Remove default build of darwin/386

cmd/build.go
Fix prometheus/node_exporter#1836.  The underlying bug is essentially the same as prometheus/node_exporter#698, and the fix here is essentially the same as #88.  Neither illumos nor Solaris supports static linking to these system libraries.
With this change, using the same setup as described in prometheus/node_exporter#1836, I'm able to build node_exporter.
=> Fix cgo builds on illumos by avoiding static linking

cmd/tarball.go, doc/examples/crossbuild/.promu.yml, doc/examples/crossbuild/Makefile, doc/examples/crossbuild/README.md, main_test.go
On Windows systems tar isn't available by default. This change creates
additional archives in the ZIP format. The tar.gz archive format on
Windows platform is kept for backwards compatibility as some users might
have written custom release scripts assuming this format.
Fixes #46
=> Produce ZIP archives for Windows releases

README.md, cmd/crossbuild.go, cmd/promu.go
Handle the platforms list in crossbuild with a regexp. Allows for
simpler build lists like `promu crossbuild -p linux`.
* Mostly backwards compatible.
* Eliminiates the need to maintain an ARM alias list.
=> Use regexp for crossbuild platforms

cmd/build.go
Allow to override build date with SOURCE_DATE_EPOCH
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This PR was done while working on [reproducible builds for
openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
Signed-off-by: Witek Bedyk <witold.bedyk@suse.com>
=> Set build date from SOURCE_DATE_EPOCH

cmd/checksum_test.go, cmd/crossbuild_tarballs.go, cmd/promu.go, pkg/repository/info.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
=> Remove ioutil

.promu.yml, cmd/build.go, cmd/promu.go
This is needed because of regressions in go1.19 which uses DNS resolution from go and can't resolve localhost anymore.
https://github.com/prometheus/prometheus/issues/11480
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> Add the ability to override tags per GOOS

cmd/build.go
Allow to overwrite build user if SOURCE_DATE_EPOCH is set in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Do not discover user/host for reproducible builds

doc/examples/prometheus/.promu.yml
```bash
cd doc/exmaple/prometheus
promu build
```
I got
```txt
Unable to parse config file: .promu.yml
!! yaml: unmarshal errors:
line 1: field verbose not found in type cmd.Config
```
1. In `/doc/examples/prometheus/.promu.yml#L1`, there is a `verbose` parameter.
https://github.com/prometheus/promu/blob/570796fcc6310e062a6bc17cf981887b16b2a8fa/doc/examples/prometheus/.promu.yml#L1
2. However, there is no verbose parameter in  `Promu Command Configuration`
https://github.com/prometheus/promu/blob/570796fcc6310e062a6bc17cf981887b16b2a8fa/cmd/promu.go#L44
3.Therefore, an error occurred while parsing the configuration
https://github.com/prometheus/promu/blob/570796fcc6310e062a6bc17cf981887b16b2a8fa/cmd/promu.go#L150
=> fix exmaple/prometheus build error

README.md, cmd/codesign.go, cmd/promu.go
Calls on `rcodesign` to code sign a target binary.
TODO:
=> Add codesign utility function

cmd/build.go
The use of `go.cgo` in the config file is the intended method of controlling `CGO_ENABLED`. This is intentional and by design to make sure the build environment is controlled by promu.
Reverts prometheus/promu#327
=> Revert "improve: honor CGO_ENABLED env variable if it is set"

cmd/version.go
Use Println to correctly print the short version string with a newline.
* Also fixes govet error.
=> Fix short version print

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile.common, cmd/build.go, cmd/check.go, cmd/checksum.go, cmd/crossbuild.go, cmd/tarball.go
- Migrate the configuration file
- Update the tooling version and CI
- Apply auto-fixes
Supersedes #342
xref: https://github.com/prometheus/prometheus/pull/16356
Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>
=> chore: Upgrade golangci-lint to v2
