cmd/build.go, doc/examples/.promu.yml
=> Remove goversion ldflag

cmd/build.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/tarball.go
=> Add a default value for the build.binaries config based on project name

cmd/build.go, cmd/crossbuild_tarballs.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/tarball.go
=> Fatal if project's version is not found + fatalMsg() improvement

README.md
=> Add a link to the Prometheus component Builds RFC

cmd/build.go, cmd/promu.go
=> Always set -s ldflag for darwin to fix dwarf error when cross-building

cmd/build.go
Fixes https://circleci.com/gh/sdurrheimer/node_exporter/42 error
=> Fix darwin cross-build ldflags handling

cmd/build.go, cmd/crossbuild.go, cmd/crossbuild_tarballs.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/tarball.go
=> Make 'repository.path' required for 'build' and 'crossbuild' commands

cmd/crossbuild.go, cmd/promu.go, vendor/github.com/mcuadros/go-version/LICENSE, vendor/github.com/mcuadros/go-version/README.md, vendor/github.com/mcuadros/go-version/compare.go, vendor/github.com/mcuadros/go-version/constraint.go, vendor/github.com/mcuadros/go-version/doc.go, vendor/github.com/mcuadros/go-version/group.go, vendor/github.com/mcuadros/go-version/normalize.go, vendor/github.com/mcuadros/go-version/sort.go, vendor/github.com/mcuadros/go-version/stability.go, vendor/vendor.json
=> Use a single list of platforms to crossbuild

cmd/crossbuild.go
@sdurrheimer 
Anything else needed? The pushes happen in the repo's respective ̀circle.yml` files, so it seems to be it.
=> Use Quay base image

cmd/crossbuild.go, cmd/promu.go
=> Abort crossbuild on error

cmd/release.go
@sdurrheimer Any other place aside from the repositories' `circle.yaml` where we need to update?
=> use v-prefixed versions

cmd/promu.go, cmd/release.go, util/retry/retry.go
=> Add retry mechanism for github release uploads

doc/examples/.promu.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prometheus/promu/38)
=> Update doc example

cmd/info.go
Fixes prometheus/prometheus#1748
=> Use full Git revision instead of short

cmd/crossbuild.go, cmd/promu.go
To match https://github.com/prometheus/golang-builder/pull/16
=> Update Go version to 1.7.4.

cmd/crossbuild.go, cmd/promu.go
=> Use go1.8.1 by default

circle.yml, cmd/build.go, cmd/checksum.go, cmd/crossbuild.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/tarball.go, vendor/github.com/pkg/errors/LICENSE, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/appveyor.yml, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/stack.go, vendor/vendor.json
+ display stackstrace with the `verbose` flag.
=> Use pkg/errors for custom errors and wrapping message

cmd/build.go, cmd/crossbuild.go
=> Force CGO_ENABLED envvar to 0 when cgo flag is not set.

Makefile
* Build `staticcheck` binary.
* Run staticcheck test.
=> Add staticchck to Makefile

cmd/build.go
While working in `prometheus/prometheus` I wanted to be able to run `make build` and only build `promtool` instead of both `promtool` and `prometheus`. Rather than commenting out one of the binaries in the yaml file every time, I made some changes to promu to allow for a comma separated string of binary names to be passed to the `build` command.
Building a single binary looks like this:
```$make build BINARIES=promtool
>> fetching promu
>> building binaries
>   promtool
```
Building all looks like this:
```
$make build                  
>> fetching promu
>> building binaries
>   prometheus
>   promtool
```
or this:
```
$make build BINARIES=all     
>> fetching promu
>> building binaries
>   prometheus
>   promtool
```
And trying to build a binary that is not present in your yaml file: …
=> add functionality to optionally build one or more binary from promu.yml

.travis.yml, circle.yml, cmd/crossbuild.go, cmd/promu.go
+ Use Go 1.9.0 in Travis and Circleci
=> Bump default go version to 1.9.0

cmd/build.go, cmd/checksum_test.go, cmd/info.go, cmd/promu.go, cmd/release.go, cmd/version.go
Hi @sdurrheimer ,
I fixed some trivial [gometalinter](https://github.com/alecthomas/gometalinter) issues.
Thanks!
=> Gometalinter fixes

cmd/crossbuild.go, cmd/promu.go
@krasi-georgiev this is the change you wanted.
=> Change to using Go 1.10.0 by default

cmd/crossbuild.go
=> Add support for 32bit MIPS.

Makefile.common, cmd/crossbuild.go, cmd/promu.go, doc/examples/.promu.yml
Added changes for building promu on s390x. Also modified the crossbuild.go to add s390x support.
Can someone please review the changes?
=> Adding changes to support s390x

.circleci/config.yml, .travis.yml, cmd/crossbuild.go, cmd/promu.go, doc/examples/.promu.yml
Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>
=> Bump Go version to 1.11

doc/examples/prometheus/README.md
Signed-off-by: yeya24 <ben.ye@daocloud.io>
=> fix a typo promtheus -> prometheus

README.md
Signed-off-by: dongwenjuan <dong.wenjuan@zte.com.cn>
=> fix the path of .promu.yml in README file

cmd/info.go
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
=> Fallback to git describe output if no VERSION files provided

.circleci/config.yml, .travis.yml, cmd/promu.go, doc/examples/prometheus/.promu.yml
Updating the go version 1.12.*
=> bump go version to 1.12 for promu

cmd/tarball.go
Fixes https://github.com/prometheus/promu/issues/132
=> cmd/tarball: restore --prefix flag

cmd/release.go
=> cmd/release: add --timeout option

cmd/crossbuild.go, doc/examples/prometheus/.promu.yml
Closes: https://github.com/prometheus/promu/issues/150
=> Add aix/ppc64 to supported builds.

cmd/release.go, cmd/release_test.go
=> improve error handling when parsing CHANGELOG

cmd/build.go
ref https://github.com/prometheus/prometheus/pull/5966
cc @SuperQ  
Signed-off-by: Hrishikesh Barman <hrishikeshbman@gmail.com>
=> updated helptext for promu build args

README.md
=> README.md: update required Go version

util/sh/sh.go
Signed-off-by: Julius Volz <julius.volz@gmail.com>
=> Remove unused Quote() function

cmd/crossbuild.go
Closes #199
Closes #191
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Add Apple Silicon and Illumos

.circleci/config.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Use current branch to build promu

.circleci/config.yml, cmd/crossbuild.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Enable circleci parallelism

cmd/crossbuild.go, cmd/promu.go
Use the new single crossbuild image to handle CGO builds.
=> Simplify CGO crossbuilds

cmd/crossbuild.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Add windows/arm64

cmd/promu.go
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> yaml: Use unmarshalstrict

.golangci.yml, cmd/build.go, cmd/check.go, cmd/checksum.go, cmd/checksum_test.go, cmd/crossbuild.go, cmd/crossbuild_tarballs.go, cmd/promu.go, cmd/release.go, cmd/tarball.go, pkg/changelog/changelog.go, pkg/repository/info.go, pkg/repository/info_test.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> enable errorlint, gocritic, gofumpt, goimports, revive linters

go.mod, go.sum, pkg/repository/info.go
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> use github.com/Masterminds/semver/v3

.circleci/config.yml
Add missing release context for access to publishing secrets.
=> Fix release context

.circleci/config.yml, .promu.yml, go.mod, go.sum
* Update build to Go 1.23.
* Update minimum version to 1.22.
=> Upgrade Go to 1.23

.golangci.yml
chore: clean up and sort golangci-lint configuration
=> chore: clean up and sort golangci-lint configuration
